### ISSUE TITLE
If running more than one job, data is empty after the first job is run

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/spotnik#1]
in main()

**Comment by joshiemoore** [comment]
This happens because `open()`ed files are iterables which can only be iterated once, and then they are exhausted.

To fix this, you could re-open the file for each job like this:
```
for job in jobs:
    with open(ADD_LIST_FILE) as csvfile:
        data = csv.DictReader(csvfile)
    # work . . .
```

Or you could read the file into a list which you can iterate as many times as you want:
```
with open(ADD_LIST_FILE) as csvfile:
    reader = csv.DictReader(csvfile)
    data = list(reader)
for job in jobs:
    # work . . .
```

I would go with something similar to the second option.

**Comment by riverscuomo** [comment]
Fascinating. Yeah, I'll go with option two.
